application:
    appName: sgt

spring:
    mail:
        host: smtp.gmail.com
        port: 587
        username: matheus.ferreira@basis.com.br
        password: 98301310
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true
                  connectiontimeout: 5000
                  timeout: 5000
                  writetimeout: 5000
                  socketFactory:
                      port: 465
                      class: javax.net.ssl.SSLSocketFactory
    application:
        name: sgtservice
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:postgresql://localhost:5432/sgt
        username: sgt
        password: sgt
        hikari:
            poolName: Hikari
            auto-commit: false
    jackson:
        deserialization:
            fail-on-unknown-properties: false
    jpa:
#        database-platform: io.github.jhipster.domain.util.FixedPostgreSQL95Dialect
        database: POSTGRESQL
        show-sql: true
        open-in-view: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
    liquibase:
        change-log: classpath:/db/master.xml
#        drop-first: true
server:
    port: 8080
    error:
        include-message: always


TWILIO_ACCOUNT_SID: "AC078366af0e78d8c68ac2bcdc26d4cefa"
TWILIO_AUTH_TOKEN:  "ba8df80f77a1094bf9fd68352584ca94"
